server:
  port: 8080
  servlet:
    context-path: /cash-track

spring:
  application:
    name: ms-shooter-account
  datasource:
    url: jdbc:postgresql://localhost:5432/cash_track_db # ${DB_URL}
    username: postgres # ${DB_USERNAME}
    password: pass # ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

app-security:
  password-encoder:
    bCryptStrength: 5 # ${BCRYPT_STRENGTH}

s3:
  minio:
    url: { MINIO_URL }
    access-key: { MINIO_ACCESS_KEY }
    secret-key: { MINIO_SECRET_KEY }
    bucket:
      transactions:{ MINIO_TRANSACTIONS_BUCKET }